Troubleshooting section with Minio
epinio/docs pull request #195
Opened 2022-12-06 14:08 UTC by thehejik

Ref. https://github.com/epinio/epinio/issues/1856

Added new section for troubleshooting containing page about accessing Minio S3-compatible service.

2022-12-06 14:25 UTC, andreas-kupries requested changes
Just phrasing changes. Best to have @nunix have a look at them too.
Still have to test the code segments.

2022-12-06 14:25 UTC, andreas-kupries commented on docs/troubleshooting/minio.md
> +sidebar_label: "Accessing internal Minio service"
```suggestion
sidebar_label: "Accessing Epinio's Internal Minio Service"
```

2022-12-06 14:25 UTC, andreas-kupries commented on docs/troubleshooting/minio.md
> +# Accessing internal MinIO service
```suggestion
# Accessing Epinio's Internal MinIO Service
```

2022-12-06 14:25 UTC, andreas-kupries commented on docs/troubleshooting/minio.md
> +There are several ways to make an internal S3-compatible MinIO service available for debugging purposes. In this document, we will cover only two of them, exposing the Minio-console web interface and
```suggestion
There are several ways to make Epinio's internal S3-compatible MinIO service available for debugging purposes. In this document, we will cover only two of them, first exposing the Minio-console web interface and then accessing the Minio service through the AWS CLI. In both cases we will expose the internal service through a kubernetes `NodePort` service.
```

2022-12-06 14:25 UTC, andreas-kupries commented on docs/troubleshooting/minio.md
> +For security reasons, make sure that you've deleted the exposed services immediately at the end of your debugging session.
```suggestion
For security reasons, make sure that you deleted the exposed services immediately at the end of your debugging session.
```

2022-12-06 14:25 UTC, andreas-kupries commented on docs/troubleshooting/minio.md
> +Simplest way to access internal Minio service is by using a web browser. Copy the block below and paste it to the terminal with configured access to your kubernetes cluster.
```suggestion
The simplest way to access Epinio's internal Minio service is by using a web browser. Copy the block below and paste it to a terminal which is configured to have access to your kubernetes cluster.
```

2022-12-06 14:25 UTC, andreas-kupries commented on docs/troubleshooting/minio.md
> +Output of the last line will be similar to this one:
```suggestion
The output from the command on the last line will be similar to:
```

2022-12-06 14:25 UTC, andreas-kupries commented on docs/troubleshooting/minio.md
> +## Access Minio by using AWS CLI
```suggestion
## Access Epinio's Minio through the AWS CLI
```

2022-12-06 14:25 UTC, andreas-kupries commented on docs/troubleshooting/minio.md
> +Another method is to use AWS CLI to communicate with internal S3-compatible Minio API endpoint. If you choose this method just simply copy the block below and paste it to the terminal with configured
```suggestion
Another method is using the AWS CLI to communicate with the internal S3-compatible Minio API endpoint. If you choose this method copy the block below and paste it to a terminal which is configured to have access to your kubernetes cluster.
```

2022-12-06 14:25 UTC, andreas-kupries commented on docs/troubleshooting/minio.md
> +Install AWS CLI according to this [document](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) and configure it to access internal Minio/S3 service as follows:
```suggestion
Install AWS CLI according to Amazon's [Getting Started Guide](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) and configure it to access the internal Minio/S3 service as follows:
```

2022-12-06 14:25 UTC, andreas-kupries commented on docs/troubleshooting/minio.md
> +For information about using AWS CLI with S3, see the official [documentation](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) and also documentation from [MinIO](https:
```suggestion
For more information about using AWS CLI with S3, see Amazon's [Getting Started Guide](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) and also the documentation from [MinIO](https://min.io/docs/minio/linux/integrations/aws-cli-with-minio.html) on this topic.
```

2022-12-09 15:28 UTC, thehejik commented
I moved the document into current Howtos section instead of creating new Troubleshooting.

2022-12-12 09:06 UTC, merged