First pass review and changes.
epinio/docs pull request #283
Opened 2023-08-23 09:56 UTC by jhkrug

A few points, marked with TODO: need a closer look.

2023-08-23 14:17 UTC, andreas-kupries reviewed
Some suggestions, answers, ...

2023-08-23 14:17 UTC, andreas-kupries commented on docs/installation/install_epinio.md
> +To generate trusted TLS certificates with "Let's Encrypt" for your public domain set `.Values.global.tlsIssuer` to `letsencrypt-production` and your e-mail to the value for the `.Values.global.tlsIss
```suggestion
To generate trusted TLS certificates with "Let's Encrypt" for your public domain set `.Values.global.tlsIssuer` to `letsencrypt-production` and the value for the `.Values.global.tlsIssuerEmail` key to your e-mail.
```

2023-08-23 14:17 UTC, andreas-kupries commented on docs/installation/install_epinio.md
> +The Public Cloud How-to describes the three major cloud providers but Epinio can run on any Kubernetes cluster.
Maybe link to this how to ?

2023-08-23 14:17 UTC, andreas-kupries commented on docs/installation/install_epinio.md
> +If you already have kubed, you can skip installation by setting
```suggestion
If you already have `kubed`, you can skip installation by setting
```

2023-08-23 14:17 UTC, andreas-kupries commented on docs/installation/install_epinio.md
> +Using s3gw set the custom storageClass by the value of `.Values.s3gw.storageClass.name`.
```suggestion
When using s3gw set the custom storageClass as the value of `.Values.s3gw.storageClass.name`.
```

(and minio equivalently)

2023-08-23 14:17 UTC, andreas-kupries commented on docs/installation/install_epinio.md
> +<!--TODO: Not sure about using a hashed blob, is that OK? Presumably to guarantee a line number reference?-->
Yes. A non-hashed reference, i.e. by branch name can shift what it points to, as the file changes on the branch.

2023-08-23 14:17 UTC, andreas-kupries commented on docs/installation/install_epinio.md
> +to store that image in container registry. Epinio installs a container registry
```suggestion
to store that image in a container registry. Epinio installs a container registry
```

2023-08-23 14:41 UTC, jhkrug commented on docs/installation/install_epinio.md
> +The Public Cloud How-to describes the three major cloud providers but Epinio can run on any Kubernetes cluster.
I will do.

2023-08-23 15:04 UTC, andreas-kupries approved these changes

2023-08-24 09:15 UTC, andreas-kupries requested changes
Small nit, otherwise looks ok to me.

2023-08-24 09:15 UTC, andreas-kupries commented on docs/installation/install_epinio.md
> +- If you receive `Entity Too Large` errors when [uploading](https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#custom-max-body-size) application
```suggestion
- If you receive `Entity Too Large` errors when [uploading](https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#custom-max-body-size) application source code into Epinio, you need to increase the `proxy-body-size` with `--set 'ingress.annotations.nginx\.ingress\.kubernetes\.io/proxy-body-size=1000m'`
```

nit.

2023-08-24 09:31 UTC, andreas-kupries approved these changes

2023-08-24 09:36 UTC, merged