Merge all Public Cloud docs in one file
epinio/docs pull request #48
Opened 2022-01-20 10:56 UTC by ldevulder

2022-01-20 14:32 UTC, andreas-kupries requested changes
Noticed an issue in inherited text which was not changed, and, IMHO, is in need of an update. Best do it now.

2022-01-20 14:35 UTC, juadk requested changes

2022-01-20 14:35 UTC, juadk commented on src/installation/install_epinio_on_public_cloud.md
> +If you don't have an existing cluster, follow the [quickstart](https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough) to create an AKS cluster.
```suggestion
If you do not have an existing cluster, follow the [quickstart](https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough) to create an AKS cluster.
```

2022-01-20 14:35 UTC, juadk commented on src/installation/install_epinio_on_public_cloud.md
> +If you don't have an existing cluster, follow the [quickstart](https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html) to create an EKS cluster.
```suggestion
If you do not have an existing cluster, follow the [quickstart](https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html) to create an EKS cluster.
```

2022-01-20 14:35 UTC, juadk commented on src/installation/install_epinio_on_public_cloud.md
> +If you don't have an existing cluster, follow the [quickstart](https://cloud.google.com/kubernetes-engine/docs/quickstart) to create a GKE cluster.
```suggestion
If you do not have an existing cluster, follow the [quickstart](https://cloud.google.com/kubernetes-engine/docs/quickstart) to create a GKE cluster.
```

2022-01-20 14:35 UTC, juadk commented on src/installation/install_epinio_on_rancher_desktop.md
> +If you don't want to use the default "magic" DNS please follow [Install Epinio with custom DNS](install_epinio_customDNS.md).
```suggestion
If you do not want to use the default "magic" DNS please follow [Install Epinio with custom DNS](install_epinio_customDNS.md).
```

2022-01-20 14:42 UTC, juadk commented on src/installation/system_requirements.md
>  - Kubernetes versions 1.18 .. 1.21
This is not the scope of this PR but I think we need to update this too:
Feel free to commit it or I can do it in another PR.
```suggestion
- Kubernetes versions 1.20 .. 1.23
```

2022-01-20 15:55 UTC, ldevulder commented on src/installation/install_epinio_on_public_cloud.md
> +- For test environments, this should work on nearly any kubernetes distribution. Epinio will try to automatically create a magic DNS domain, e.g. **10.0.0.1.omg.howdoi.website**.
Sure, I will change this.

2022-01-20 16:08 UTC, juadk approved these changes

2022-01-21 09:24 UTC, ldevulder commented on src/installation/install_epinio_on_public_cloud.md
> +- For test environments, this should work on nearly any kubernetes distribution. Epinio will try to automatically create a magic DNS domain, e.g. **10.0.0.1.omg.howdoi.website**.
In fact yes the "magic" DNS cannot be used on Public Clouds tests, so better to remove it.
And I will add the command to explain how to get the IP address, it's the one provided at the end of the helm installation in fact.

2022-01-21 10:16 UTC, ldevulder commented on src/installation/install_epinio_on_public_cloud.md
> +- For test environments, this should work on nearly any kubernetes distribution. Epinio will try to automatically create a magic DNS domain, e.g. **10.0.0.1.omg.howdoi.website**.
For K3d there is already the needed information to get the IP address, will add it for K3s.

2022-01-21 10:18 UTC, ldevulder commented on src/installation/install_epinio_on_public_cloud.md
> +- For test environments, this should work on nearly any kubernetes distribution. Epinio will try to automatically create a magic DNS domain, e.g. **10.0.0.1.omg.howdoi.website**.
Should be better now, let me know :-)

2022-01-21 10:23 UTC, andreas-kupries approved these changes
LGTM

2022-01-21 10:25 UTC, andreas-kupries commented on src/installation/install_epinio_on_public_cloud.md
> +- For test environments, this should work on nearly any kubernetes distribution. Epinio will try to automatically create a magic DNS domain, e.g. **10.0.0.1.omg.howdoi.website**.
Looks good. Approved.

2022-01-21 11:22 UTC, merged