How to debug an app
epinio/docs pull request #73
Opened 2022-03-15 15:40 UTC by enrichman

As stated in

- https://github.com/epinio/epinio/issues/601#issuecomment-1067899229  

at the moment we cannot customize the build phase, so it's not possible to enable the debug for the languages that needs a flag during build time.

This PR is just going to remove the debug from the port-forward page, to add a dedicated debug how-to.

- Ref: https://github.com/epinio/docs/issues/56

2022-03-15 15:57 UTC, andreas-kupries requested changes

2022-03-16 08:02 UTC, enrichman commented on src/howtos/debug.md
> +This how-to demonstrates how to debug a running application.
Hm, actually not, but I couldn't find a list of the supported languages. I'll make it more generic then, removing the Java references.

2022-03-18 13:21 UTC, andreas-kupries requested changes

2022-03-18 13:21 UTC, andreas-kupries commented on src/howtos/debug.md
> +To debug a Java application you need to set the [`BPL_DEBUG_ENABLED`](https://paketo.io/docs/howto/java/#enable-remote-debugging) environment variable to `true`.
```suggestion
To debug a Java application you have to set the [`BPL_DEBUG_ENABLED`](https://paketo.io/docs/howto/java/#enable-remote-debugging) environment variable to `true`.  
```

2022-03-18 13:21 UTC, andreas-kupries commented on src/howtos/debug.md
> +After the application has restarted (to integrate the change of the environment) you can use [port forwarding](port_forwarding.md) to attach the debugger that will run by default on the port `8000`:
```suggestion
After the application has restarted (to integrate the change of the environment) use [port forwarding](port_forwarding.md) to attach the debugger. It runs by default on the port `8000`:
```

2022-03-18 13:21 UTC, andreas-kupries commented on src/howtos/debug.md
> +To debug a Node application you will need to start the application with the `--inspect` flag, so your `package.json will be:
```suggestion
To debug a Node application you will have to start the application with the `--inspect` flag. Your `package.json` has to be similar to:
```

2022-03-18 13:21 UTC, andreas-kupries commented on src/howtos/debug.md
> +After the application has been deployed you can use [port forwarding](port_forwarding.md) to attach the debugger that will run by default on the port `9229`:
```suggestion
After the application has been deployed use [port forwarding](port_forwarding.md) to attach the debugger. It runs by default on the port `9229`:
```

2022-03-18 13:24 UTC, andreas-kupries approved these changes

2022-03-18 13:25 UTC, merged